### ISSUE TITLE
4 more WIC proxy functions

### ISSUE THREAD

**Issue by GCuser99** [fafalone/WinDevLib#25]
You probably missed them because they are the only ones not preceded by "I"?

WICCreateImagingFactory_Proxy
WICCreateColorContext_Proxy
WICCreateColorTransform_Proxy
WICSetEncoderFormat_Proxy

Thanks!

**Comment by fafalone** [comment]
3 of those I already have for the next update, but WICCreateColorTransform_Proxy... I missed that one because it's not even exported from windowscodecs.dll, but instead from WindowsCodecsExt.dll. Along with a IWICColorTransform_Initialize_Proxy that you missed too I found in the export table of that dll.

**Comment by fafalone** [comment]
Available now in v8.0.402, thanks for reporting!
