### ISSUE TITLE
Duplicate definition: WOW64_LDT_ENTRY

### ISSUE THREAD

**Issue by mwolfe02** [fafalone/WinDevLib#32]
Looks like WOW64_LDT_ENTRY is defined twice in the wdAPI.twin file:

![image](https://github.com/fafalone/WinDevLib/assets/305213/f755cdb2-1f6d-4cd0-8856-ecd1798fa0f4)

_Note: I'm using version 8.3.432.0 of WinDevLib_

**Comment by fafalone** [comment]
Could you update WDL and confirm if the issue is still present? (Current version is 8.3.430 so I'm thinking typo and you have an older one; I can't repro in current version. Type appears exactly once on 7865.)

**Comment by fafalone** [comment]
I apologize for not looking at this closer sooner; I have no idea how this issue got past me into the public release, since while it only impacted 64bit I always check for errors in both, and had no memory of fixing it, no idea why I wouldn't note it, and even less of an idea how it went on for 2 stealth updates. LOL

This is now fixed in v8.3.437, thanks for reporting!

**Comment by mwolfe02** [comment]
No worries, Jon.  I'm sorry I didn't get a chance to follow-up myself any earlier.  Glad to hear it's fixed, though.  Honestly, this package might be more immediately useful for Access developers than twinBASIC itself (at least for the time being).
